### ISSUE TITLE
Invalid option :versioned provided to relation :versions

### ISSUE THREAD

**Issue by AndreiMotinga** [simi/mongoid-versioning#11]
I'm trying to update app from rails 4 to rails 5, which required mongoid > 5. with it mongoid-versioning fails with 

```
➜  cms git:(rails-5) ✗ be rails s
=> Booting WEBrick
=> Rails 5.0.6 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
[2017-12-19 13:12:33] INFO  WEBrick 1.3.1
[2017-12-19 13:12:33] INFO  ruby 2.3.3 (2016-11-21) [x86_64-darwin16]
[2017-12-19 13:12:33] INFO  WEBrick::HTTPServer#start: pid=33566 port=3000
Started GET "/admin/articles" for ::1 at 2017-12-19 13:12:51 -0500
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from add_before_filter at /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:9)

Mongoid::Errors::InvalidOptions (
message:
  Invalid option :versioned provided to relation :versions.
summary:
  Mongoid checks the options that are passed to the relation macros to ensure that no ill side effects occur by letting something slip by.
resolution:
  Valid options are: as, cascade_callbacks, cyclic, order, store_as, before_add, after_add, before_remove, after_remove, class_name, counter_cache, extend, inverse_class_name, inverse_of, name, relation, validate, make sure these are the ones you are using.):

app/models/article.rb:4:in `include'
app/models/article.rb:4:in `<class:Article>'
app/models/article.rb:1:in `<top (required)>'
app/controllers/admin/articles_controller.rb:1:in `<top (required)>'
  Rendering /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (4.2ms)
  Rendering /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.7ms)
  Rendering /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (21.2ms)
  Rendered /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (179.4ms)
```

**Comment by jsierrakrlead** [comment]
no updates?
